version: '3.7'

services:
  app:
    container_name: portfolio
    build:
      context: ./src/
      target: server
    restart: always
    # env_file:
    #   - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx
    healthcheck:
      test:  wget -q -t 1 --spider http://localhost || exit 1
      interval: 5m
      timeout: 3s
    networks:
      - default
      # - nginx-proxy_default

# networks:
#   nginx-proxy_default:
#     external: true
